name: Update Dataset

on:
  schedule:
    - cron: "5 11 * * *"  # 07:05 ET daily
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt

      # Optional: repo-level variables to narrow scope (safe if unset)
      - name: Configure optional filters
        run: |
          echo "COVERAGE_STATES=${{ vars.COVERAGE_STATES }}" >> $GITHUB_ENV
          echo "COVERAGE_STATUS=${{ vars.COVERAGE_STATUS }}" >> $GITHUB_ENV
          echo "COVERAGE_CONTRACTORS=${{ vars.COVERAGE_CONTRACTORS }}" >> $GITHUB_ENV
          echo "COVERAGE_MAX_DOCS=${{ vars.COVERAGE_MAX_DOCS }}" >> $GITHUB_ENV
          echo "COVERAGE_TIMEOUT=${{ vars.COVERAGE_TIMEOUT }}" >> $GITHUB_ENV

      # ✅ Run as a module so 'from scripts.*' imports work
      - name: Run dataset build
        run: python -m scripts.run_once

      - name: Commit dataset if changed
        run: |
          git config user.name "dataset-bot"
          git config user.email "dataset-bot@users.noreply.github.com"
          git add dataset data || true
          if git diff --cached --quiet; then
            echo "No dataset changes."
          else
            git commit -m "Dataset update $(date -u +'%Y-%m-%d')"
            git push
          fi

      # 📦 Bundle a stable buyer artifact (always the same filename)
      - name: Bundle ZIP artifact
        run: |
          mkdir -p artifacts
          zip -j artifacts/cms_lcd_lca_dataset_latest.zip dataset/*.csv

      - name: Create Release with artifact
        uses: softprops/action-gh-release@v2
        with:
          tag_name: "run-${{ github.run_id }}-${{ github.run_number }}"
          name: "Dataset Update ${{ github.run_number }}"
          body: |
            Automated CMS LCD/LCA dataset update.

            Includes:
            - documents_latest.csv
            - document_codes_latest.csv
            - changes_YYYY-MM.csv

            Stable artifact for buyers:
            - cms_lcd_lca_dataset_latest.zip
          files: |
            artifacts/cms_lcd_lca_dataset_latest.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
