name: Coverage Harvest (Sharded)

on:
  workflow_dispatch: {}
  schedule:
    - cron: "0 7 * * *"   # Daily at 07:00 UTC (~03:00 AM ET)

# Prevent overlapping runs of this workflow (keeps logs/results cleaner)
concurrency:
  group: coverage-harvest-sharded
  cancel-in-progress: false

jobs:
  harvest:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      # If needed, limit how many shards run simultaneously:
      # max-parallel: 8
      matrix:
        shard: [0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15]
        total: [16]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"
          cache-dependency-path: |
            requirements.txt
            **/requirements.txt

      - name: Install dependencies
        if: hashFiles('requirements.txt') != ''
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run shard ${{ matrix.shard }}/${{ matrix.total }}
        env:
          SHARD_INDEX: ${{ matrix.shard }}
          SHARD_TOTAL: ${{ matrix.total }}
          # Optional: cap work per job if a shard still approaches 6h
          # COVERAGE_MAX_DOCS: "1200"
        run: |
          mkdir -p .harvest_logs
          python -m scripts.run_once 2>&1 | tee .harvest_logs/shard-${{ matrix.shard }}.log
          test ${PIPESTATUS[0]} -eq 0

      - name: Upload shard log
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: harvest-logs-shard-${{ matrix.shard }}
          path: .harvest_logs/shard-${{ matrix.shard }}.log
          if-no-files-found: error
