name: Coverage Harvest (Sharded)

on:
  workflow_dispatch: {}
  schedule:
    - cron: "0 7 * * *"   # Daily at 07:00 UTC (~03:00 AM ET)

jobs:
  harvest:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        shard: [0, 1, 2, 3]   # adjust to control parallelism (e.g., 8 or 12)
        total: [4]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        id: setup-python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: ${{ runner.os }}-pip-

      - name: Install dependencies
        if: hashFiles('requirements.txt') != ''
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Ensure git available
        run: |
          git --version || (sudo apt-get update && sudo apt-get install -y git)
          git ls-files | wc -l

      - name: Run shard ${{ matrix.shard }}/${{ matrix.total }}
        env:
          SHARD_INDEX: ${{ matrix.shard }}
          SHARD_TOTAL: ${{ matrix.total }}
          SHARD_BATCH_SIZE: "50"   # files per batch; tune based on your harvester
        run: |
          python scripts/harvest_shard.py

      - name: Upload artifact (per-shard logs)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: harvest-logs-shard-${{ matrix.shard }}
          path: |
            .harvest_logs/**
            **/harvest_shard_*.log
          if-no-files-found: ignore
