name: Coverage Harvest (Sharded)

on:
  workflow_dispatch:
  schedule:
    - cron: "0 7 * * *"

concurrency:
  group: coverage-harvest-sharded
  cancel-in-progress: false

jobs:
  harvest:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    strategy:
      fail-fast: false
      matrix:
        shard: [0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15]
        total: [16]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
          else
            pip install requests tenacity pandas pyyaml
          fi

      - name: Run shard
        env:
          COVERAGE_STATES:      ${{ vars.COVERAGE_STATES }}
          COVERAGE_STATUS:      ${{ vars.COVERAGE_STATUS }}
          COVERAGE_CONTRACTORS: ${{ vars.COVERAGE_CONTRACTORS }}
          COVERAGE_MAX_DOCS:    ${{ vars.COVERAGE_MAX_DOCS }}
          COVERAGE_TIMEOUT:     ${{ vars.COVERAGE_TIMEOUT }}
          COVERAGE_SHARD_INDEX: ${{ matrix.shard }}
          COVERAGE_SHARD_TOTAL: ${{ matrix.total }}
        run: |
          mkdir -p .harvest_logs dataset
          python -m scripts.run_once 2>&1 | tee .harvest_logs/shard-${{ matrix.shard }}.log
          test ${PIPESTATUS[0]} -eq 0

      - name: Upload shard log
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: harvest-logs-shard-${{ matrix.shard }}
          path: .harvest_logs/shard-${{ matrix.shard }}.log
          if-no-files-found: error

      - name: Upload shard dataset (codes)
        if: success() || failure()
        uses: actions/upload-artifact@v4
        with:
          name: document_codes_shard_${{ matrix.shard }}
          path: dataset/document_codes_latest.zip
          if-no-files-found: warn

      - name: Upload shard dataset (no codes)
        if: success() || failure()
        uses: actions/upload-artifact@v4
        with:
          name: document_nocodes_shard_${{ matrix.shard }}
          path: dataset/document_nocodes_latest.csv
          if-no-files-found: warn
