# .github/workflows/coverage-harvest.yml
name: Coverage Harvest

on:
  workflow_dispatch:
  schedule:
    - cron: "0 7 * * *"

concurrency:
  group: coverage-harvest
  cancel-in-progress: false

jobs:
  harvest:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
          else
            pip install requests tenacity pandas pyyaml
          fi

      - name: Run harvest
        env:
          COVERAGE_STATES:      ${{ vars.COVERAGE_STATES }}
          COVERAGE_STATUS:      ${{ vars.COVERAGE_STATUS }}
          COVERAGE_CONTRACTORS: ${{ vars.COVERAGE_CONTRACTORS }}
          COVERAGE_MAX_DOCS:    ${{ vars.COVERAGE_MAX_DOCS }}
          COVERAGE_TIMEOUT:     ${{ vars.COVERAGE_TIMEOUT }}
        run: |
          mkdir -p .harvest_logs dataset
          python -m scripts.run_once 2>&1 | tee .harvest_logs/run_once.log
          test ${PIPESTATUS[0]} -eq 0

      - name: Upload dataset (codes CSV)
        uses: actions/upload-artifact@v4
        with:
          name: document_codes_latest_csv
          path: dataset/document_codes_latest.csv
          if-no-files-found: error

      - name: Upload dataset (codes ZIP)
        uses: actions/upload-artifact@v4
        with:
          name: document_codes_latest_zip
          path: dataset/document_codes_latest.zip
          if-no-files-found: warn

      - name: Upload dataset (no codes)
        uses: actions/upload-artifact@v4
        with:
          name: document_nocodes_latest
          path: dataset/document_nocodes_latest.csv
          if-no-files-found: warn

      - name: Upload run log
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: harvest-log
          path: .harvest_logs/run_once.log
          if-no-files-found: error
